CREATE DATABASE IF NOT EXISTS PROJECT_DEV
    COMMENT = 'Development database for project-one';

USE DATABASE PROJECT_DEV;

CREATE SCHEMA IF NOT EXISTS ONE_RAW_V001
    COMMENT = 'Raw data landing zone for project-one';

CREATE DCM PROJECT IF NOT EXISTS PROJECT_DEV.ONE_RAW_V001.PROJECT_ONE;
