-- RULE 16: GRANT ALL PRIVILEGES
GRANT SELECT, INSERT ON TABLE IOTI_RAW_TB_DATA TO ROLE ANALYST;
GRANT ALL ON TABLE IOTI_RAW_TB_DATA TO ROLE ADMIN_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA IOT_RAW_V001 TO ROLE POWER_USER;

-- RULE 17: ACCOUNTADMIN in scripts
USE ROLE CICD;
USE ROLE ACCOUNTADMIN;
GRANT ROLE CICD TO ROLE ACCOUNTADMIN;

-- RULE 18: Plaintext passwords
CREATE USER IF NOT EXISTS SVC_ETL TYPE = SERVICE DEFAULT_ROLE = ETL_ROLE;
ALTER USER SVC_BAD SET PASSWORD = 'NewPassword456';
