-- RULE 8: Schema maturity prefix
CREATE SCHEMA IF NOT EXISTS RAW_test_v001;
CREATE SCHEMA IF NOT EXISTS CUR_test_v001;
CREATE SCHEMA IF NOT EXISTS test_no_prefix_v001;

-- RULE 9: Schema version suffix
CREATE SCHEMA IF NOT EXISTS RAW_sensors_v001;
CREATE SCHEMA IF NOT EXISTS RAW_sensors_no_version;

-- RULE 10: Table names must follow {DOM}{COMP}_{MAT}_{TB}_ pattern
CREATE OR REPLACE TABLE IOTI_RAW_TB_SENSOR_READINGS (ID INT);
CREATE OR REPLACE TABLE SENSOR_READINGS (ID INT);

-- RULE 11: View names must follow {DOM}{COMP}_{MAT}_{VW}_ pattern
CREATE OR REPLACE VIEW IOTI_RAW_VW_SENSOR_OVERVIEW AS SELECT 1;
CREATE OR REPLACE VIEW SENSOR_OVERVIEW AS SELECT 1;

-- RULE 12: Dynamic Table names must follow {DOM}{COMP}_{MAT}_{DT}_ pattern
CREATE OR REPLACE DYNAMIC TABLE IOTI_AGG_DT_HOURLY_STATS TARGET_LAG = '5 MINUTES' WAREHOUSE = MD_TEST_WH AS SELECT 1;
CREATE OR REPLACE DYNAMIC TABLE HOURLY_STATS TARGET_LAG = '5 MINUTES' WAREHOUSE = MD_TEST_WH AS SELECT 1;

-- RULE 13: Stage naming
CREATE OR REPLACE STAGE ICGI_RAW_ST_SWIFT_INBOUND FILE_FORMAT = (TYPE = XML);
CREATE OR REPLACE STAGE ICG_RAW_SWIFT_INBOUND FILE_FORMAT = (TYPE = XML);

-- RULE 26: File Format naming
CREATE OR REPLACE FILE FORMAT ICGI_RAW_FF_XML TYPE = XML;
CREATE OR REPLACE FILE FORMAT XML_FILE_FORMAT TYPE = XML;

-- RULE 27: Stored Procedure naming
CREATE OR REPLACE PROCEDURE IOTI_AGG_SP_CALCULATE_AVERAGES() RETURNS STRING LANGUAGE SQL AS 'SELECT 1';
CREATE OR REPLACE PROCEDURE CALC_AVERAGES() RETURNS STRING LANGUAGE SQL AS 'SELECT 1';

-- RULE 28: Task naming
CREATE OR REPLACE TASK IOTI_RAW_TK_INGEST_HOURLY WAREHOUSE = MD_TEST_WH SCHEDULE = 'USING CRON 0 * * * * UTC' AS SELECT 1;
CREATE OR REPLACE TASK HOURLY_INGEST WAREHOUSE = MD_TEST_WH SCHEDULE = 'USING CRON 0 * * * * UTC' AS SELECT 1;
