-- =============================================================================
-- SQLCC:C016: IN/NOT IN is used for a subquery (prefer EXISTS)
-- =============================================================================

-- POSITIVE TESTS (compliant - must NOT trigger rule)
SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA A
WHERE EXISTS (SELECT 1 FROM ONEO_RAW_TB_WH_SIZE_RECOMMENDATION B WHERE B.BYTES_SCANNED_LOWER = A.SENSOR_ID);

SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA WHERE SENSOR_ID IN (1, 2, 3);

-- NEGATIVE TESTS (non-compliant - MUST trigger rule)
SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA
WHERE SENSOR_ID IN (SELECT BYTES_SCANNED_LOWER FROM ONEO_RAW_TB_WH_SIZE_RECOMMENDATION);

SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA
WHERE SENSOR_ID NOT IN (SELECT BYTES_SCANNED_LOWER FROM ONEO_RAW_TB_WH_SIZE_RECOMMENDATION);
