-- RULE 23: ORDER BY in views
CREATE OR REPLACE VIEW IOTI_RAW_VW_SENSORS AS SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA;
CREATE OR REPLACE VIEW IOTI_RAW_VW_SORTED_BAD AS SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA ORDER BY SENSOR_ID;

-- RULE 24: COPY INTO without ON_ERROR
COPY INTO IOTI_RAW_TB_INGEST FROM @IOTI_RAW_ST_LANDING FILE_FORMAT = (TYPE = CSV) ON_ERROR = 'CONTINUE';
COPY INTO IOTI_RAW_TB_INGEST FROM @IOTI_RAW_ST_LANDING FILE_FORMAT = (TYPE = CSV);

-- RULE 25: Dynamic Table without TARGET_LAG
CREATE OR REPLACE DYNAMIC TABLE IOTI_AGG_DT_VALID TARGET_LAG = '5 MINUTES' WAREHOUSE = MD_TEST_WH AS SELECT 1;
CREATE OR REPLACE DYNAMIC TABLE IOTI_AGG_DT_MISSING_LAG WAREHOUSE = MD_TEST_WH AS SELECT 1;
