-- RULE 19: SELECT *
SELECT SENSOR_ID, SENSOR_0 FROM IOTI_RAW_TB_SENSOR_DATA;
SELECT * FROM IOTI_RAW_TB_SENSOR_DATA;

-- RULE 20: FLOAT/DOUBLE
CREATE OR REPLACE TABLE IOTI_RAW_TB_NUMBERS_OK (AMOUNT NUMBER(18,2));
CREATE OR REPLACE TABLE IOTI_RAW_TB_FLOAT_BAD (SENSOR_VAL FLOAT);
CREATE OR REPLACE TABLE IOTI_RAW_TB_DOUBLE_BAD (MEASUREMENT DOUBLE);
CREATE OR REPLACE TABLE IOTI_RAW_TB_REAL_BAD (READING REAL);

-- RULE 21: VARCHAR without explicit length
CREATE OR REPLACE TABLE IOTI_RAW_TB_VARCHAR_OK (NAME VARCHAR(100), CITY VARCHAR(255));
CREATE OR REPLACE TABLE IOTI_RAW_TB_VARCHAR_BAD (NAME VARCHAR, CITY VARCHAR );

-- RULE 22: CREATE TABLE must include COMMENT
CREATE OR REPLACE TABLE IOTI_RAW_TB_COMMENTED (ID INT) COMMENT = 'Table with proper comment';
CREATE OR REPLACE TABLE IOTI_RAW_TB_NO_COMMENT (ID INT);

-- RULE 23: ORDER BY in views
CREATE OR REPLACE VIEW IOTI_RAW_VW_SENSORS_OK AS SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA;
CREATE OR REPLACE VIEW IOTI_RAW_VW_SORTED_BAD AS SELECT SENSOR_ID FROM IOTI_RAW_TB_SENSOR_DATA ORDER BY SENSOR_ID;

-- RULE 24: COPY INTO without ON_ERROR
COPY INTO IOTI_RAW_TB_INGEST FROM @IOTI_RAW_ST_LANDING FILE_FORMAT = (TYPE = CSV) ON_ERROR = 'CONTINUE';
COPY INTO IOTI_RAW_TB_INGEST FROM @IOTI_RAW_ST_LANDING FILE_FORMAT = (TYPE = CSV);

-- RULE 25: Dynamic Table without TARGET_LAG
CREATE OR REPLACE DYNAMIC TABLE IOTI_AGG_DT_VALID TARGET_LAG = '5 MINUTES' WAREHOUSE = MD_TEST_WH AS SELECT 1;
CREATE OR REPLACE DYNAMIC TABLE IOTI_AGG_DT_MISSING_LAG WAREHOUSE = MD_TEST_WH AS SELECT 1;
