-- RULE 7: TIMESTAMP_NTZ and TIMESTAMP_LTZ
CREATE OR REPLACE TABLE IOTI_RAW_TB_TS_VALID (CREATED_AT TIMESTAMP_TZ);
CREATE OR REPLACE TABLE IOTI_RAW_TB_TS_NTZ (LOAD_TS TIMESTAMP_NTZ);
CREATE OR REPLACE TABLE IOTI_RAW_TB_TS_LTZ (SESSION_TS TIMESTAMP_LTZ);
