-- RULE 1: CREATE SCHEMA without IF NOT EXISTS or REPLACE
CREATE SCHEMA IF NOT EXISTS RAW_test_v001;
CREATE OR REPLACE SCHEMA RAW_test_v002;
CREATE SCHEMA RAW_test_v003;

-- RULE 2: CREATE TABLE without IF NOT EXISTS or REPLACE
CREATE OR REPLACE TABLE IOTI_RAW_TB_VALID (ID INT);
CREATE TABLE IF NOT EXISTS IOTI_RAW_TB_VALID2 (ID INT);
CREATE TABLE IOTI_RAW_TB_MISSING_GUARD (ID INT);

-- RULE 3: Hardcoded database/schema prefix
CREATE OR REPLACE TABLE IOTI_RAW_TB_CLEAN (ID INT);
CREATE TABLE IF NOT EXISTS DATAOPS.IOT_RAW_V001.IOTI_RAW_TB_PREFIXED (ID INT);

-- RULE 4: GRANT to PUBLIC
GRANT SELECT ON TABLE IOTI_RAW_TB_DATA TO ROLE ANALYST;
GRANT SELECT ON TABLE IOTI_RAW_TB_DATA TO PUBLIC;

-- RULE 5: DROP without IF EXISTS
DROP TABLE IF EXISTS IOTI_RAW_TB_OLD;
DROP TABLE IOTI_RAW_TB_UNSAFE;
DROP DYNAMIC TABLE IOTI_RAW_DT_UNSAFE;

-- RULE 6: USE statements
USE DATABASE DATAOPS;
USE SCHEMA IOT_RAW_V001;
USE ROLE CICD;
