DEFINE VIEW {{db}}.{{schema}}.IOTI_RAW_VW_ALL_SENSORS
AS
SELECT
    SENSOR_ID AS ID,
    SENSOR_0 AS TYPE,
    SENSOR_1,
    SENSOR_2,
    SENSOR_3
FROM {{db}}.{{schema}}.IOT_RAW;

DEFINE VIEW {{db}}.{{schema}}.IOTI_RAW_VW_SENSOR_12
AS
SELECT
    SENSOR_ID AS ID,
    SENSOR_0 AS TYPE,
    SENSOR_1,
    SENSOR_2,
    SENSOR_3
FROM {{db}}.{{schema}}.IOT_RAW
WHERE SENSOR_ID = 12;

DEFINE VIEW {{db}}.{{schema}}.IOTI_RAW_VW_SENSOR_102_AVG
AS
SELECT
    AVG(SENSOR_0) AS AVG_102
FROM {{db}}.{{schema}}.IOT_RAW
WHERE SENSOR_ID = 102;
