DEFINE TABLE {{db}}.{{schema}}.IOT_RAW (
    SENSOR_ID NUMBER(38,0),
    SENSOR_0 FLOAT,
    SENSOR_1 FLOAT,
    SENSOR_2 FLOAT,
    SENSOR_3 FLOAT,
    SENSOR_4 FLOAT,
    SENSOR_5 FLOAT,
    SENSOR_6 FLOAT,
    SENSOR_7 FLOAT,
    SENSOR_8 FLOAT,
    SENSOR_9 FLOAT,
    SENSOR_10 FLOAT,
    SENSOR_11 FLOAT
)
CHANGE_TRACKING = TRUE
COMMENT = 'Raw IOT sensor readings with 12 sensor channels';