DEFINE TABLE {{db}}.{{schema}}.IOTI_RAW_TB_SENSOR_DATA (
    SENSOR_ID NUMBER(38,0),
    SENSOR_0 NUMBER(38,6),
    SENSOR_1 NUMBER(38,6),
    SENSOR_2 NUMBER(38,6),
    SENSOR_3 NUMBER(38,6),
    SENSOR_4 NUMBER(38,6),
    SENSOR_5 NUMBER(38,6),
    SENSOR_6 NUMBER(38,6),
    SENSOR_7 NUMBER(38,6),
    SENSOR_8 NUMBER(38,6),
    SENSOR_9 NUMBER(38,6),
    SENSOR_10 NUMBER(38,6),
    SENSOR_11 NUMBER(38,6)
)
CHANGE_TRACKING = TRUE
COMMENT = 'Raw IOT sensor readings with 12 sensor channels';

DEFINE TABLE {{db}}.{{schema}}.ONEO_RAW_TB_WH_SIZE_RECOMMENDATION (
    MIN_BYTES NUMBER(38,0),
    MAX_BYTES NUMBER(38,0),
    WH_SIZE VARCHAR(20)
)
COMMENT = 'Warehouse size recommendation lookup table';
