name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipeline:
    uses: zbrainiac-labs/DataOpsBackbone/.github/workflows/dataops-pipeline.yml@main
    with:
      SOURCE_DATABASE: PROJECT_DEV
      SOURCE_SCHEMA: ONE_RAW_V001
      DCM_PROJECT_IDENTIFIER: PROJECT_DEV.ONE_RAW_V001.PROJECT_ONE
      DCM_TARGET: DEV
    secrets: inherit
